# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d21ad0dc9e815f7008cc01d9c4733b43a2d3b8f373e9ea28bacf8282979afa3ef723a3c86443d3b08aae1b1bad142d6faf734384d09149401015bcf983e2a097

test:
  secret_key_base: 46995f53a23050b40ccde8db59d5a2d4f814c7dad02f053aadf7be21b773fd9cc7e1a75dafbce83b0fe35dcf4d6177d39d48c171d01530d49420088ac55807e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
